version: "3.3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  db:
    image: "mysql:5.7"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
